profile: cover.out
local-prefix: github.com/GoToolSharing/htb-cli
threshold:
  file: 0
  package: 0
  total: 0

override:
  - threshold: 100
    path: ^pkg/lib/foo$

exclude:
  paths:
    - \.pb\.go$
    - ^pkg/bar