profile: cover.out
local-prefix: github.com/GoToolSharing/htb-cli
threshold:
  file: 1
  package: 1
  total: 5

override:
  - threshold: 100
    path: ^pkg/lib/foo$

exclude:
  paths:
    - \.pb\.go$
    - ^pkg/bar