name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19', '1.20', '1.21']
        os: [ 'linux', 'windows', 'darwin' ]
        arch: [ 'amd64', 'arm64' ]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: go build -v ./...

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Check test and generate coverage
      env:
        GOOS: linux
        GOARCH: amd64
        HTB_TOKEN: ${{ secrets.HTB_TOKEN_SECRET }}
      run: go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

    - name: Check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        config: ./.testcoverage.yml
        profile: cover.out
        local-prefix: github.com/GoToolSharing/htb-cli
        threshold-file: 80
        threshold-package: 80
        threshold-total: 95

    - name: make coverage badge
      uses: action-badges/core@0.2.2
      with:
        label: coverage
        message: ${{ steps.coverage.outputs.badge-text }}
        message-color: ${{ steps.coverage.outputs.badge-color }}
        file-name: coverage.svg
        badge-branch: badges
        github-token: "${{ secrets.GITHUB_TOKEN }}"