name: golangci-lint

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-pkg-cache: true
        skip-build-cache: true

    - name: Upload lint results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: golangci-lint-results
        path: golangci-lint-report.txt
